### ISSUE TITLE
Oregon tile support

### ISSUE THREAD

**Issue by dhodcz2** [VIDA-NYU/tile2net#12]
Would greatly appreciate having Oregon added to the supported region catalogue. Imagery from 2017/2018 is currently publicly available, and splits between:
- [Eastern half of Oregon](https://imagery.oregonexplorer.info/arcgis/rest/services/OSIP_2017/OSIP_2017_WM/ImageServer)
- [Western half of Oregon](https://imagery.oregonexplorer.info/arcgis/rest/services/OSIP_2018/OSIP_2018_WM/ImageServer)

_Originally posted by @sylvan-sh in https://github.com/VIDA-NYU/tile2net/issues/11#issuecomment-1513478999_

**Comment by dhodcz2** [comment]
[https://github.com/VIDA-NYU/tile2net/blob/69ee4ef87568022e1e8ee00704a6a1d257423869/src/tile2net/raster/source.py#L198](Oregon has been implemented on tile2net/dhodcz2). However, we are unable to an SSL error:

`requests.exceptions.SSLError: HTTPSConnectionPool(host='imagery.oregonexplorer.info', port=443): Max retries exceeded with url: /arcgis/rest/services/OSIP_2018/OSIP_2018_WM/ImageServer/tile/19/190540/82893 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))
`

Are you associated Oregon Explorer? Is this source only intended to be available to users affiliated with Oregon Explorer? @sylvan-sh

**Comment by jthiard** [comment]
The SSL certificate for `imagery.oregonexplorer.info` is OK when opening in a browser, but verification will fail when trying from python requests or curl

```
$ curl -I https://imagery.oregonexplorer.info
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

Usually it means that the SSL chain is not properly configured on the server which fails to seend one or many intermediate certificates. Browsers use a big curated list of trusted certificates to avoid this error in most case, but tools like python requests does not (not part of the job!). See https://github.com/psf/requests/issues/2959#issuecomment-168961838 for a better explanation.

The best option is to contact the server admin to report the issue and get this fixed upstream.

**Comment by sylvan-sh** [comment]
@jthiard, your explanation is very helpful, as I was seeing the same thing. I have some contacts I can reach out to that are affiliated with the source, and hopefully we can get this resolved. Will update once I hear something.

**Comment by Mary-h86** [comment]
@jthiard Thank you for the helpful comment! 
@sylvan-sh Would be great if you could reach out to your contacts there and update us, so we can resolve the issue  so you can easily use Tile2Net for your region!

**Comment by Mary-h86** [comment]
@sylvan-sh 
Hi Sylvan, 
Do you have any updates on the Oregon tiles?

**Comment by sylvan-sh** [comment]
Unfortunately, nothing definitive. The correct people to make the change have been informed, but that happened back in late April after you, @Mary-h86, and @jthiard helped identify the issue. I'm still actively pursuing getting this resolved, ideally w/ even more current tiles, and will jubilantly post to this issue once accomplished.

**Comment by Mary-h86** [comment]
@sylvan-sh 
Thanks for the update! Looking forward to adding Oregon to our list of supported cities!

**Comment by sylvan-sh** [comment]
@Mary-h86, exciting news! I believe the certificate issue has now been addressed. Additionally, we have [a new tile set that both provides a unified Oregon set and was collected in 2022](https://imagery.oregonexplorer.info/arcgis/rest/services/OSIP_2022/OSIP_2022_WM/ImageServer). I just ran a mid-sized city in Oregon w/ the 2022 imagery, and it looks like everything executed w/o problems. Thank you for being so patient while the process for a fix played out.

**Comment by Mary-h86** [comment]
> @Mary-h86, exciting news! I believe the certificate issue has now been addressed. Additionally, we have [a new tile set that both provides a unified Oregon set and was collected in 2022](https://imagery.oregonexplorer.info/arcgis/rest/services/OSIP_2022/OSIP_2022_WM/ImageServer). I just ran a mid-sized city in Oregon w/ the 2022 imagery, and it looks like everything executed w/o problems. Thank you for being so patient while the process for a fix played out.

That's great!! Happy to hear and thank you for sharing it with us!
