### ISSUE TITLE
Tile stitching for supported regions often fails

### ISSUE THREAD

**Issue by stl-emilyeros** [VIDA-NYU/tile2net#16]
I encountered several problems testing Tile2Net on supported regions. I think the supported regions are not alll in the expected resolution, and the directories may be mapped incorrectly. Details.

I installed tile2net in a virtual environment (Google Colab) with CUDA-enabled GPU and it ran successfully for the example Boston project. The command I ran was a version of this, tailored to the specific area:
`! cd tile2net && python3 -m tile2net generate -l "34.20817698321565, -118.3882312786859, 33.93434881788897, -118.0251130179942" -o "out_la_test" -n la_test | python3 -m tile2net inference
`
Here's a list of where I tested tile2net and the results/errors:

- Boston: No errors, output polygons and network looked reasonable in GIS
- Cambridge: No errors, output polygons and network looked reasonable in GIS
- Amherst, MA: Failed. All static tiles were solid black rectangles… and the parent folder for the tiles was named “ny” (see screenshot below). I think the imagery extractor pointed to the wrong tile catalog, passed the Amherst coordinates, and returned with these unusable pngs.
<img width="1846" alt="amherst" src="https://github.com/VIDA-NYU/tile2net/assets/85912030/e0247fcb-c494-457a-bc28-de0f724c8a73">
- DC: Failed. Static tiles had 512x512 resolution instead of the expected 256x256. Static tiles were downloaded but stitching failed. Coordinates used: `38.90741993704333, -77.04672763112193, 38.90050854988334, -77.03766438685489`. Screenshot of resulting static tile and python error:
<img width="1787" alt="image" src="https://github.com/VIDA-NYU/tile2net/assets/85912030/66a06609-5e74-402c-ab1d-099eb1b56fb8">
- Seattle. Succeeded in small area (`47.62086099319143, -122.34357515528596, 47.61685734761309, -122.33637702990318`). Failed in larger area. I will try to reproduce and add additional detail.

**Comment by Mary-h86** [comment]
@stl-emilyeros 
Thank you for pointing these out. It’s very helpful that you are testing different regions. 
We will investigate the issues and report back when the bugs are fixed. 

Regarding DC, the base size is 512 (the only region up to now in our catalogue with this base). But the stitch failing is definitely a bug on our side, and thank you for detecting it!

**Comment by dhodcz2** [comment]
Thank you for your detailed feedback. We have resolved the issues with Amherst and DC. Please pull the latest version from the repo. Can you provide more information on the failure that occurred when Seattle was run with a large area?

**Comment by stl-emilyeros** [comment]
Sorry for my delay. I re-tried the Amherst, Seattle, and DC test areas and they ran successfully. Thanks for addressing the issue I filed!
