### ISSUE TITLE
Tile Service Support

### ISSUE THREAD

**Issue by dhodcz2** [VIDA-NYU/tile2net#2]
This thread is reserved for the discussion of tile services to be supported. 
If cached tiles of high-resolution orthorectified imagery is publicly available for your region, you can submit a request here for your region to be added to our supported region catalogue, which enables automatic download and processing of the tiles by Tile2Net.
To do that, please add a post to this thread, with the link to the publicly available hosted tiles. If the tiles follow the same XYZ tiling convention currently supported by Tile2Net, we will add support for your region shortly (depending on the number of requests).

**Comment by Mary-h86** [comment]
If you have access to cached tiles of high-resolution orthorectified imagery for your region, you can request to have your region added to our supported region catalogue. This will enable Tile2Net to automatically download and process the tiles. To make a request, please follow these steps:

1. Add a post to this thread with a link to the publicly available hosted tiles.
2. Ensure that the tiles follow the same XYZ tiling convention currently supported by Tile2Net.
3. Wait for us to review your request and add support for your region (depending on the number of requests).

Thank you for helping us expand the reach of Tile2Net!
