### ISSUE TITLE
Inference is stuck

### ISSUE THREAD

**Issue by rafiibnsultan** [VIDA-NYU/tile2net#21]
I tried to run the "inference" notebook, but it is stuck on the inference stage (seems like it). After 9 hours, I stopped the execution. Is this normal behavior? There is no progress bar to figure out if it is actually running or not.

**Comment by dhodcz2** [comment]
Thanks for taking your time to help improve tile2net. Two questions:
1. Are you able to run [example.sh](https://github.com/VIDA-NYU/tile2net/blob/main/examples/example.sh)? 
2. Would you please try running this again, and giving us the logger output?
Thanks.

**Comment by rafiibnsultan** [comment]
The python files are working, the problem happens with the jupyter notebook. Could be an issue regarding the conda environment, I will get back to you after checking it out.

**Comment by Mary-h86** [comment]
@rafiibnsultan 
Thank you. Did you do a git pull? Could you report the logs after pulling the most recent version?
Also, did you create a new virtual environment to install?
