### ISSUE TITLE
where is the model definition

### ISSUE THREAD

**Issue by xiaojianggis** [VIDA-NYU/tile2net#24]
Great work. I check the repository and your papers, however, I didn't find the model definition. I am wondering how you construct the model and train it. Thanks.

**Comment by Mary-h86** [comment]
@xiaojianggis 
Thank you! As described in the paper, the pipeline has tow main parts, feature detection and network generation. Feature detection which uses a semantic segmentation model  is detailed in section 3.1 of the paper, the implementation in section 3.2, and training results in section 3.3. Section 3.4 details the network creation parts. 

The code for the semantic segmentation part is available under tileseg directory. 

The trained weights are also available, and will be automatically downloaded as part of the model set-up.

**Comment by xiaojianggis** [comment]
Thanks. Found it.
