### ISSUE TITLE
Input_dir failed to parse

### ISSUE THREAD

**Issue by Jiayingpdf** [VIDA-NYU/tile2net#25]
Hi,
I tried to run the jupyter notebook, using input_dir parameter to read local tiles. But the ValueError always came out:

ValueError: input_dir failed to parse 'C:/Jiaying/tile2net/19/271188/192329.png' 

For the format of input_dir parameter, I tried two ways. But both ways triggered the same issue. 

1. input_dir='C:/xxx/tile2net/19/271188/192329.png'
2. input_dir='C:/xxx/tile2net/19/271188_192329.png'

Thank you :)

**Comment by Jiayingpdf** [comment]
Thank you very much. 

My images can be inpuuted and processed. I tried with the images in Munich old town, the image segmentation can be generated successfully. But I met an error when running interfenrence:

`CalledProcessError                        Traceback (most recent call last)
Cell In[14], line 1
----> 1 raster.inference()

File C:\Jiaying\tile2net\src\tile2net\raster\validate.py:31, in validate.__call__(self, *args, **kwargs)
     25 # if self.name == 'generate':
     26 #     print('Generating')
     27 #
     28 # if self.name == 'inference':
     29 # print('Inference')
     30 assert raster.tiles.shape == (raster.width, raster.height)
---> 31 result = self.func(raster, *args, **kwargs)
     33 # print('Done')
     35 return result

File C:\Jiaying\tile2net\src\tile2net\raster\raster.py:835, in Raster.inference(self, eval_folder)
    833 if eval_folder:
    834     args.extend(['--eval_folder', str(eval_folder)])
--> 835 subprocess.run(args, check=True)

File ~\AppData\Local\Programs\Python\Python310\lib\subprocess.py:526, in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    524     retcode = process.poll()
    525     if check and retcode:
--> 526         raise CalledProcessError(retcode, process.args,
    527                                  output=stdout, stderr=stderr)
    528 return CompletedProcess(process.args, retcode, stdout, stderr)

CalledProcessError: Command '['python', 'C:\\Jiaying\\tile2net\\src\\tile2net', 'inference', '--city_info', 'C:\\Jiaying\\Munich Oldtown\\tiles\\Munich Oldtown_256_info.json']' returned non-zero exit status 1.`

**Comment by Jiayingpdf** [comment]
> SACFsv

>

**Comment by Jiayingpdf** [comment]
1. asdv
2. 

- [ ] asdfasd
/asdvfasdbv asd

**Comment by dhodcz2** [comment]
I have updated the logging to be more expressive. Please switch to the dhodcz2 branch and paste the traceback here once again:
```
git switch dhodcz2
git fetch
```

**Comment by Mary-h86** [comment]
@Jiayingpdf 
I wanted to check in with you and see if your issue has been resolved.

Thank you, 
Maryam

**Comment by Jiayingpdf** [comment]
Yes, it works perfectly for me. Thank you!

**Comment by Mary-h86** [comment]
@Jiayingpdf 
Thank you, glad to hear that! I am closing this issue. Feel free to re-open if you need.
