### ISSUE TITLE
Step by step of How implement Tile2Net in my own city ? 

### ISSUE THREAD

**Issue by ambarja** [VIDA-NYU/tile2net#34]
This is fantastic software!!!! 🚀 
I would like to implement it in my own image that was taken with a drone in my city.
I would like to know how I can implement in my zone, I revised the issue #18, I understand that the first step is to have tiles of my drone images, rigth?
Thank you very much in advance!

### Characteristic of my drone image
 - **CRS:** 4326
 - **FORMAT:** .tif
 - **SPATIAL RESOLUTION:** 2cmx2cm
<hr/>

### Step 01
The **first step** is generate tiles of my drone image in **QGIS** using the **Generate XYZ tiles (Directory)**
What valors I should put in the number **1**, **2**, **3** ,**4**, **5**
Is correct to have always tiles of **256x256**? 

![image](https://github.com/VIDA-NYU/tile2net/assets/23284899/513c7fa7-8f3b-4a43-a47a-119c07a64969)

**Comment by Mary-h86** [comment]
@ambarja 
Thank you! and great work collecting aerial images for your city. 
To convert your aerial imagery to tiles, first you need to orthorectify them. This is a key step to create any planimetric data from imagery.  Once you have the orthorectified imagery, then you can use the QGIS tool, and depending on the resolution of the imagery you collected, you can pass the minimum and maximum zoom levels (lets say 19 and 20, or you can pass both 1 and 2 as 20). Leave DPI (3) at 96, change the background to be black, and leave 4,5 as it is. 
Don't forget to set it to be saved to a directory.

Next, you will have your images tiled up and saved in a folder. Lets say that you have your tiles on zoom level 20. 
To run the model, you should pass the path where your tiles are saved, as <path to your tile folders>/20/x/y.png, follow the instructions to generate results with your own data and we would love to see how it goes! 

Good Luck

**Comment by ambarja** [comment]
@Mary-h86 Thanks you very much.
I will follow the recommended instructions.

**Comment by Mary-h86** [comment]
@ambarja Happy to help! I will close this issue. Feel free to re-open if you have any questions in this regard.

**Comment by ambarja** [comment]
## Step 02 
@Mary-h86 recently I generated my own tiles of my drone image with QGIS.
Here the output

![tilesss](https://github.com/VIDA-NYU/tile2net/assets/23284899/5d53015b-9426-4014-8e7d-6a059923b562)

However, when I run my code in Google Colab I have problems, so how can I implement my own image with tile2net? 

![image](https://github.com/VIDA-NYU/tile2net/assets/23284899/be9fdb59-b188-4bc2-afd6-5910a2c9504d)
