### ISSUE TITLE
issue while cloning

### ISSUE THREAD

**Issue by sumitmishra209** [VIDA-NYU/tile2net#39]
while running git clone git@github.com:VIDA-NYU/tile2net.git

the error is 
Cloning into 'tile2net'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
-------------------------------
If manually download then no setup file in tile2net folder, and dependency compatibility issue is coming if installed without proper version info.

**Comment by dhodcz2** [comment]
Thank you for your interest in Tile2Net. Regarding this issue, it appears that you do not have SSH configured. ChatGPT believes this to be the case, and I was able to replicate your issue by removing my SSH key from my ~/.ssh directory. Here's GPT-4's output:

The error you encountered pertains to a lack of appropriate SSH keys in your GitHub configuration. Here's a succinct resolution:

1. **SSH Key Generation and Addition**: If you don't have an SSH key or haven't added it to your GitHub account, create one and link it. Use:
   ```bash
   ssh-keygen -t rsa -b 4096 -C "your_email@example.com"
   ssh-add ~/.ssh/id_rsa
   ```
   Copy the content of `~/.ssh/id_rsa.pub` to GitHub SSH keys in your account settings.

2. **Clone Using HTTPS Instead**: If SSH is not necessary, you can clone using HTTPS, which doesn't require SSH key configuration. Replace the SSH URL with the HTTPS URL, e.g.:
   ```bash
   git clone https://github.com/VIDA-NYU/tile2net.git
   ```



For more in-depth information, you can read the official GitHub guide on this issue [here](https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey#make-sure-you-have-a-key-that-is-being-used).
