### ISSUE TITLE
Receiving a "formatters" key error

### ISSUE THREAD

**Issue by moatazkilany** [VIDA-NYU/tile2net#6]
Hi, I'm trying to run tile2net on windows. It seems that there is an issue with AttrDict and Namespace imports.
The import produces an error

`from tile2net.namespace import AttrDict, Namespace
Traceback (most recent call last):
  Cell In[4], line 1
    from tile2net.namespace import AttrDict, Namespace

  File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\tile2net\__init__.py:13
    from tile2net.raster.raster import Raster

  File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\tile2net\raster\raster.py:41
    from tile2net.logger import logger

  File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\tile2net\logger.py:9
    pipe(

  File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\toolz\functoolz.py:628 in pipe
    data = func(data)

  File ~\AppData\Local\Programs\Python\Python310\lib\logging\config.py:72 in fileConfig
    formatters = _create_formatters(cp)

  File ~\AppData\Local\Programs\Python\Python310\lib\logging\config.py:105 in _create_formatters
    flist = cp["formatters"]["keys"]

  File ~\AppData\Local\Programs\Python\Python310\lib\configparser.py:965 in __getitem__
    raise KeyError(key)

KeyError: 'formatters'`

After some debugging, it's coming from an inner call for import in config.py : `from tile2net.tileseg.utils.attr_dict import AttrDict`

Any idea where is this coming from or how to resolve?
I Installed all requirements
Thank you.

**Comment by dhodcz2** [comment]
Thank you for raising this issue. This issue has been resolved. Please reinstall the latest version of tile2net. Originally we had the user install with the flag -e to circumvent this problem but that is no longer necessary.
