### ISSUE TITLE
Running tile2net in colab

### ISSUE THREAD

**Issue by Narjes97** [VIDA-NYU/tile2net#68]
Hi, 
I was wondering if I could run tile2net in colab. It has GPU and I have installed the required packages and I have clone the repo. 

![Capture1](https://github.com/VIDA-NYU/tile2net/assets/123910941/a8f577cf-94b5-402e-af42-5084bdd01442)

![Capture2](https://github.com/VIDA-NYU/tile2net/assets/123910941/3e7b8b8c-faf1-4024-863d-719d51d92654)

But when I try to run the first command of the example file, I get this error:

![Capture3](https://github.com/VIDA-NYU/tile2net/assets/123910941/0f0abcb1-9d4c-4e6c-b583-daf966492046)

Can you please guide me?

**Comment by Mary-h86** [comment]
@Narjes97 
The problem is that you haven’t installed tile2net there! 
You can follow the steps described here: https://github.com/VIDA-NYU/tile2net/blob/main/docs/source/notebooks/colab_example.ipynb
