### ISSUE TITLE
Question on inference.ipynb

### ISSUE THREAD

**Issue by gwyong** [VIDA-NYU/tile2net#70]
Thank you for your amazing work.

When I ran the `inference.ipynb`, I got this error.

raster.project

---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
Cell In[6], [line 1](vscode-notebook-cell:?execution_count=6&line=1)
----> [1](vscode-notebook-cell:?execution_count=6&line=1) raster.project

File c:\Users\gwyong1\AppData\Local\anaconda3\envs\umich-env1\Lib\functools.py:995, in cached_property.__get__(self, instance, owner)
    [993](file:///C:/Users/gwyong1/AppData/Local/anaconda3/envs/umich-env1/Lib/functools.py:993) val = cache.get(self.attrname, _NOT_FOUND)
    [994](file:///C:/Users/gwyong1/AppData/Local/anaconda3/envs/umich-env1/Lib/functools.py:994) if val is _NOT_FOUND:
--> [995](file:///C:/Users/gwyong1/AppData/Local/anaconda3/envs/umich-env1/Lib/functools.py:995)     val = self.func(instance)
    [996](file:///C:/Users/gwyong1/AppData/Local/anaconda3/envs/umich-env1/Lib/functools.py:996)     try:
    [997](file:///C:/Users/gwyong1/AppData/Local/anaconda3/envs/umich-env1/Lib/functools.py:997)         cache[self.attrname] = val

File c:\Users\gwyong1\Desktop\src\tile2net\src\tile2net\raster\grid.py:610, in Grid.project(self)
    [608](file:///C:/Users/gwyong1/Desktop/src/tile2net/src/tile2net/raster/grid.py:608) @cached_property
    [609](file:///C:/Users/gwyong1/Desktop/src/tile2net/src/tile2net/raster/grid.py:609) def project(self):
--> [610](file:///C:/Users/gwyong1/Desktop/src/tile2net/src/tile2net/raster/grid.py:610)     return Project(
    [611](file:///C:/Users/gwyong1/Desktop/src/tile2net/src/tile2net/raster/grid.py:611)         name=self.name,
    [612](file:///C:/Users/gwyong1/Desktop/src/tile2net/src/tile2net/raster/grid.py:612)         outdir=self.output_dir,
    [613](file:///C:/Users/gwyong1/Desktop/src/tile2net/src/tile2net/raster/grid.py:613)         raster=self,
    [614](file:///C:/Users/gwyong1/Desktop/src/tile2net/src/tile2net/raster/grid.py:614)     )

File c:\Users\gwyong1\Desktop\src\tile2net\src\tile2net\raster\project.py:551, in Project.__init__(self, name, outdir, raster)
    [549](file:///C:/Users/gwyong1/Desktop/src/tile2net/src/tile2net/raster/project.py:549) path = Path(self.__fspath__())
    [550](file:///C:/Users/gwyong1/Desktop/src/tile2net/src/tile2net/raster/project.py:550) path.mkdir(parents=True, exist_ok=True)
--> [551](file:///C:/Users/gwyong1/Desktop/src/tile2net/src/tile2net/raster/project.py:551) free = psutil.disk_usage(path.__fspath__()).free
...
--> [274](file:///C:/Users/gwyong1/AppData/Local/anaconda3/envs/umich-env1/Lib/site-packages/psutil/_pswindows.py:274) total, free = cext.disk_usage(path)
    [275](file:///C:/Users/gwyong1/AppData/Local/anaconda3/envs/umich-env1/Lib/site-packages/psutil/_pswindows.py:275) used = total - free
    [276](file:///C:/Users/gwyong1/AppData/Local/anaconda3/envs/umich-env1/Lib/site-packages/psutil/_pswindows.py:276) percent = usage_percent(used, total, round_=1)

SystemError: argument 1 (impossible<bad format char>)
---------------------------------------------------------------------------

Could you please tell me any advice?

P.S. When I ran raster.input_dir, it returned the below error.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[11], [line 1](vscode-notebook-cell:?execution_count=11&line=1)
----> [1](vscode-notebook-cell:?execution_count=11&line=1) print(raster.input_dir)

TypeError: __str__ returned non-string (type NoneType)

**Comment by dhodcz2** [comment]
Thank you! 
I am unable to reproduce your error. Could you please include how you constructed `Raster`?

**Comment by gwyong** [comment]
Thank you for your quick answer.
We just download your repository and move inference.ipynb to `src` folder.
And then we used the same Raster as below.

raster = Raster(
    location=location,
    name='boston common',
    output_dir='./example_dir',
)
raster

**Comment by dhodcz2** [comment]
I noticed that that you are using Windows, however './example_dir' is a POSIX-path. I added a line of code to normalize the path based on your OS. Please checkout my branch with `git checkout dhodcz2` and attempt to run the same code. Does this fix your issue? Thank you

**Comment by gwyong** [comment]
![image](https://github.com/user-attachments/assets/8c2e3b07-d09c-4665-8e2a-eff0011f28ce)

Thank you for your help. I applied your code as the above.
But, it still does not work as the below.

![image](https://github.com/user-attachments/assets/55000dcb-ef10-4d5f-a9a4-87e010a2c3e5)

Could you please provide me more feedback?

**Comment by dhodcz2** [comment]
I have set up an environment on Windows and tried to run this, however I am not able to replicate your issue. Please set up a breakpoint at the line `        free = psutil.disk_usage(path.__fspath__()).free
`. Then create a python file with the following code:
```
from tile2net import Raster
location = "42.35555189953313, -71.07168915322092, 42.35364837213307, -71.06437423368418"
raster = Raster(
    location=location,
    name='boston common',
    output_dir='./example_dir',
)
raster
raster.project
```
Run this in the interactive debugger and check the value of `path.__fspath__()`. Does it look like this?
```
(path.__fspath__())
Out[2]: 'example_dir\\boston common'
```
I suspect that there is some discrepancy and somehow you have a POSIX path there. However when I run on Windows I have the Windows path as expected. "Bad format char" implies there is something wrong with the path of the string. It is not that the directory does not exist, because that would raise FileNotFoundError.

**Comment by gwyong** [comment]
Thank you for your help.
But, still it did not work.

When I checked `path.__fspath__()`, it is the same as you.
![image](https://github.com/user-attachments/assets/d1e55e07-df5d-4e85-9297-afd6545f51e2)

I will try it with Colab.

**Comment by gwyong** [comment]
I just found that error came from my Python version.
It did not work on Python 3.12.
If you can, please check the below.

https://github.com/giampaolo/psutil/issues/2252

**Comment by dhodcz2** [comment]
Good find and thank you for letting us know! I've disabled psutil. Please pull from the dhodcz2 branch until I merge with main

**Comment by gwyong** [comment]
Thank you for your help.
Now, all codes worked except the final line of `inference.ipynb`.
When I run `raster.inference()`, I got the below error.

![image](https://github.com/user-attachments/assets/e342dcfd-4cca-4891-a8a7-9458947d969c)

**Comment by dhodcz2** [comment]
This is due to an update in the `argh` library. In our [requirements-dev.txt](https://github.com/VIDA-NYU/tile2net/blob/842efdb5d9640a818ac00f2ab751276a9f01c785/requirements-dev.txt#L20-L19) we specify that the library requires argh==0.29.4. Please ensure you have that version installed with `pip install argh==0.29.4`

**Comment by gwyong** [comment]
Great!! Finally, it worked well. How can I check the output of `raster.inference()`?
How can I visualize the output?

I can see `tiles`, `polygons`, and `network` under `BostonCommon`.

**Comment by gwyong** [comment]
Can we visualize the output on the stitched images?

**Comment by dhodcz2** [comment]
At the moment we do not have interactively visualization available from the package in a Python environment. However you may use `raster.project` to see the stored locations of various files. The shapely file of the resulting pedestrian network will be available in the directory specified by `raster.project['network']`. The "stitched" tiles with which the inference was run will be available in the directory specified by  `raster.project['tiles']['stitched']`.

To visualize the output I recommend you use [GeoDataFrame.explore](https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.explore.html):
```
import geopandas as gpd
frame = gpd.read_file(...)
frame.explore()
```

**Comment by gwyong** [comment]
I really appreciate your comments.
